image: python:latest

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run:
  script:
    - pip install .
    # run the command here
  artifacts:
    paths:
      - build/*

test:
  script:
    - echo "Nanti perintah testnya taro disini ya gan!"


deploy:
  stage: deploy
  script:
    - python main.py
  environment: production

