
image: python:latest

before_script:
  - python --version ; pip --version 
  - pip install virtualenv
  - python -m virtualenv venv
  - find -type f -name "activate"  -path "**/.venv/**"
  - source $( `find -type f -name "activate"  -path "**/.venv/**"`)

run:
  script:
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest --cov=src --cov-report=html
  artifacts:
    paths:
      - /coverage/
    expire_in: 1 week


deploy:
  stage: deploy
  script: python main.py

