
image: python:3.12

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - python -m virtualenv venv
  - find -type f -name "activate"  -path "**/.venv/**"
  - source $( `find -type f -name "activate"  -path "**/.venv/**"`)

run:
  script:
    - pip install .
    - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest --cov=src --cov-report=html
  artifacts:
    paths:
      - /coverage/
    expire_in: 1 week


deploy:
  stage: deploy
  script:
    - python main.py
  environment: production

