stages:
  - test

unit-test:
  stage: test
  image: python:3.11
  script:
      - python.exe -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pytest --cov-report=html --cov=src
  artifacts:
    paths:
        - coverage
    expire_in: 30days